name: profiler
description: An App for profiling names with ages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  image_picker: ^1.0.2
  logging: ^1.2.0
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  dio: ^5.3.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  firebase_analytics: ^10.5.1
  firebase_core: ^2.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: PoiretOne-Regular
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf
    - family: Baskervville
      fonts:
        - asset: assets/fonts/Baskervville-Regular.ttf
        - asset: assets/fonts/Baskervville-Italic.ttf