// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdatOce1DEIs6xkmSpZfGmzKXbqAJu7lA',
    appId: '1:135039799734:web:57e626e3354064f5543117',
    messagingSenderId: '135039799734',
    projectId: 'test-app-89d4b',
    authDomain: 'test-app-89d4b.firebaseapp.com',
    storageBucket: 'test-app-89d4b.appspot.com',
    measurementId: 'G-J0F6NPE67J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7bGf9YQTWql8ONf494Fw7qJJ-7kTDEsk',
    appId: '1:135039799734:android:84889a2fe1e0118d543117',
    messagingSenderId: '135039799734',
    projectId: 'test-app-89d4b',
    storageBucket: 'test-app-89d4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBERUzYtcsxj-s75rWik3g7K_NVs0TUQ4U',
    appId: '1:135039799734:ios:efc8ee1b9ea541e0543117',
    messagingSenderId: '135039799734',
    projectId: 'test-app-89d4b',
    storageBucket: 'test-app-89d4b.appspot.com',
    iosBundleId: 'com.example.profiler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBERUzYtcsxj-s75rWik3g7K_NVs0TUQ4U',
    appId: '1:135039799734:ios:e2b212a0eb167443543117',
    messagingSenderId: '135039799734',
    projectId: 'test-app-89d4b',
    storageBucket: 'test-app-89d4b.appspot.com',
    iosBundleId: 'com.example.profiler.RunnerTests',
  );
}
